-- +goose Up
ALTER TABLE expenses
ALTER COLUMN ex_gst TYPE NUMERIC,
ALTER COLUMN gst TYPE NUMERIC,
ALTER COLUMN inc_gst TYPE NUMERIC;

-- +goose Down
ALTER TABLE expenses
ALTER COLUMN ex_gst TYPE INT,
ALTER COLUMN gst TYPE INT,
ALTER COLUMN inc_gst TYPE INT;
